spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123123123
# jpa:
#  hibernate:
#   ddl-auto: update
#   show-sql: true
 thymeleaf:
   cache: false
#   prefix: /templates/
#   suffix: .html
#   mode: LEGACYHTML5
#   encoding: UTF-8
#   servlet:
#     content-type: text/html


logging:
 level:
   root: info
   com.liufan.blog: debug
file: log/imcoding.log

mybatis:
  mapper-locations: classpath:mapper/*.xml


comment.avatar: /images/avatar.png